### 一、张量拼接与切分

1.1 torch.cat()
功能：将张量按维度dim进行拼接
tensors：张量序列
dim：要拼接的维度
1.2 torch.stack()
功能：在新创建的维度dim上进行拼接
tensors：张量序列
dim：要拼接的维度

cat不会扩张张量维度

In [3]:
import torch
t = torch.ones((2,3))
t_0 = torch.cat([t,t],dim=0)
t_1 = torch.cat([t,t],dim=1)
print(t_0,'\n',t_1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 
 tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [23]:
print(t)
t_stack = torch.stack([t,t,t,t],dim=2)
print(t_stack)
print(t_stack.size())

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.Size([2, 3, 4])


1.3 torch.chunk()
功能：将张量按维度dim进行平均切分
返回值：张量列表
注意事项：若不能整除，最后一份张量小于其他张量
input：要切分的张量
chunks：要切分的份数
dim：要切分的维度

In [31]:
t = torch.chunk(t_stack,3,2)
for idx,i in enumerate(t):
    print(i,'\n',i.shape)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]) 
 torch.Size([2, 3, 2])
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]) 
 torch.Size([2, 3, 2])


1.4 torch.split()
功能：将张量按维度dim进行切分
返回值：张量列表
tensor：要切分的张量
split_size_or_sections：为int时，表示每一份的长度；为list时，按list元素切分
dim：要切分的维度

In [36]:
t = torch.ones((2,5))
list_of_t = torch.split(t,[2,2,1],dim=1)
for idx,i in enumerate(list_of_t):
    print(i,'\n',i.shape)

tensor([[1., 1.],
        [1., 1.]]) 
 torch.Size([2, 2])
tensor([[1., 1.],
        [1., 1.]]) 
 torch.Size([2, 2])
tensor([[1.],
        [1.]]) 
 torch.Size([2, 1])


### 张量索引

2.1 torch.index_select()
功能：在维度dim上，按index索引数据
返回值：依index索引数据拼接的张量
input：要索引的张量
dim：要索引的维度
index：要索引数据的序号

In [39]:
t = torch.randint(0,9,size=(3,3))
idx = torch.tensor([0, 2], dtype=torch.long)
t_select = torch.index_select(t,dim=0,index=idx)
print("t:\n{}\nt_select:\n{}".format(t, t_select))

t:
tensor([[8, 3, 1],
        [2, 4, 7],
        [8, 4, 0]])
t_select:
tensor([[8, 3, 1],
        [8, 4, 0]])


2.2 torch.masked_select()
功能：按mask中的True进行索引
返回值：一维张量
input：要索引的张量
mask：与input同形状的布尔类型张量

In [41]:
t = torch.randint(0,9,size=(3,3))
mask = t.ge(5)# ge: greater than or equal //gt le lt
print(t)
print(mask)
t_masked = torch.masked_select(t,mask)
print(t_masked)

tensor([[7, 4, 5],
        [2, 8, 6],
        [8, 1, 6]])
tensor([[ True, False,  True],
        [False,  True,  True],
        [ True, False,  True]])
tensor([7, 5, 8, 6, 8, 6])


### 张量变换

3.1 torch.reshape
功能：变换张量形状
注意事项：当张量在内存中是连续时，新张量与input共享数据内存
input：要变换的张量
shape：新张量的形状

In [42]:
t = torch.randperm(8)
t

tensor([5, 2, 6, 0, 1, 3, 4, 7])

In [44]:
t_reshape = torch.reshape(t,(2,4))
t_reshape

tensor([[5, 2, 6, 0],
        [1, 3, 4, 7]])

In [45]:
t_reshape = torch.reshape(t,(-1,4))#-1就是自动计算
t_reshape

tensor([[5, 2, 6, 0],
        [1, 3, 4, 7]])

In [53]:
t[0]=10
print(t)
print(t_reshape)
print(id(t),'\n',id(t_reshape))
#id 不一样但是内存确实共享

tensor([10,  2,  6,  0,  1,  3,  4,  7])
tensor([[10,  2,  6,  0],
        [ 1,  3,  4,  7]])
140565921164096 
 140565921440512


3.2 torch.transpose()功能：交换张量的两个维度
input：要变换的张量
dim0：要交换的维度
dim1：要交换的维度
3.3torch.t()
功能：2维张量转置，对矩阵而言，等价于torch.transpose(input,0，1)

In [55]:
t = torch.rand((2,3,4))
t_transpose = torch.transpose(t,1,2)

In [58]:
t.shape

torch.Size([2, 3, 4])

In [59]:
t_transpose.shape

torch.Size([2, 4, 3])

3.4 torch.squeeze()
功能：压缩长度为1的维度（轴）
dim：若为None，移除所有长度为1的轴；若指定维度，当且仅当该轴长度为1时，可以被移除；
3.5 torch.unsqueeze()功能：依据dim扩展维度
dim：扩展的维度

In [61]:
t = torch.rand(1,2,3,1)
t_sq = torch.squeeze(t)
print(t_sq.shape)

torch.Size([2, 3])


In [63]:
t2 = torch.unsqueeze(t,2)
t2.shape

torch.Size([1, 2, 1, 3, 1])

### 张量数学运算

torch.add()
功能：逐元素计算input+alpha*other
input：第一个张量
alpha：乘项因子
other：第二个张量

torch.addcdiv() 
torch.addcmul()

In [67]:
t_0 = torch.randn((3,3))
print(t_0)
t_1 = torch.ones_like(t_0)
t_add = torch.add(t_0,t_1,alpha=10)
t_add

tensor([[-0.1296, -1.6888,  1.6283],
        [-0.4191,  0.9729,  0.5654],
        [-0.6119,  0.0924, -0.7600]])


tensor([[ 9.8704,  8.3112, 11.6283],
        [ 9.5809, 10.9729, 10.5654],
        [ 9.3881, 10.0924,  9.2400]])

### 线性回归
Linear Regression
求解步骤：
1. 确定模型
2. 选择损失函数
3. 求解梯度并更新w，b

In [73]:
import torch
import matplotlib.pyplot as plt
torch.manual_seed(10)

lr = 0.05  # 学习率

# 创建训练数据
x = torch.rand(20, 1) * 10  # x data (tensor), shape=(20, 1)
y = 2*x + (5 + torch.randn(20, 1))  # y data (tensor), shape=(20, 1)

# 构建线性回归参数
w = torch.randn((1), requires_grad=True)
b = torch.zeros((1), requires_grad=True)

In [ ]:
for iteration in range(1000):

    # 前向传播
    wx = torch.mul(w, x)
    y_pred = torch.add(wx, b)

    # 计算 MSE loss
    loss = (0.5 * (y - y_pred) ** 2).mean() #0.5为了消掉求导产生的的2

    # 反向传播
    loss.backward()

    # 更新参数
    b.data.sub_(lr * b.grad)
    w.data.sub_(lr * w.grad)

    # 清零张量的梯度   
    w.grad.zero_()
    b.grad.zero_()

    # 绘图
    if iteration % 20 == 0:
        plt.cla()   # 防止社区版可视化时模型重叠
        plt.scatter(x.data.numpy(), y.data.numpy())
        plt.plot(x.data.numpy(), y_pred.data.numpy(), 'r-', lw=5)
        plt.text(2, 20, 'Loss=%.4f' % loss.data.numpy(), fontdict={'size': 20, 'color':  'red'})
        plt.xlim(1.5, 10)
        plt.ylim(8, 28)
        plt.title("Iteration: {}\nw: {} b: {}".format(iteration, w.data.numpy(), b.data.numpy()))
        plt.pause(0.5)

        if loss.data.numpy() < 1:
            break
    plt.show()